### ISSUE TITLE
Node-Red crash when devicefilter is empty

### ISSUE THREAD

**Issue by reibuehl** [pattex007/node-red-contrib-fhem#2]
I am trying to read events from a FHEM dummy. The dummy can sent set devicename block and set devicename unblock events (and does according to FHEM eventlog). Since I did not receive anything on the FHEM-in node (connected to a debug node), I tried to remove the device filter just to see if I get any events but when I deployed the flow, my whole node-red instance crashed and is refusing to startup again.
In the docker container logs I see the following error:
nodered          | 16 Apr 12:48:54 - [red] Uncaught Exception:
nodered          | 16 Apr 12:48:54 - [error] TypeError: Cannot read property 'Attributes' of undefined
nodered          |     at EventEmitter.<anonymous> (/data/node_modules/node-red-contrib-fhem/fhem-input.js:84:70)
nodered          |     at EventEmitter.emit (events.js:400:28)
nodered          |     at Socket.<anonymous> (/data/node_modules/node-red-contrib-fhem/fhem-instance.js:74:36)
nodered          |     at Socket.emit (events.js:400:28)
nodered          |     at addChunk (internal/streams/readable.js:293:12)
nodered          |     at readableAddChunk (internal/streams/readable.js:267:9)
nodered          |     at Socket.Readable.push (internal/streams/readable.js:206:10)
nodered          |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
nodered          | npm ERR! code ELIFECYCLE
nodered          | npm ERR! errno 1
nodered          | npm ERR! node-red-docker@2.1.5 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
nodered          | npm ERR! Exit status 1
nodered          | npm ERR!
nodered          | npm ERR! Failed at the node-red-docker@2.1.5 start script.
nodered          | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
nodered          |
nodered          | npm ERR! A complete log of this run can be found in:
nodered          | npm ERR!     /data/.npm/_logs/2022-04-16T12_54_58_256Z-debug.log

I am able to recover the system by manually removing the FHEM-in node from flows.json but according to the Readme Devicefilter and Readingsfilter are optional, so such a behavior should not happen...

BTW: With the filter in place, the FHEM-in node shows a green "Connected" status, so I think that the connection to my FHEM instance is configured correctly - even though I don't receive the events.

**Comment by reibuehl** [comment]
I did a little bit more debugging and seem to have found the root cause for both issues - the crash and not receiving any events. The problem seems to be that the connection to FHEM is not done completely even though I get the green "Connected" status and is ultimately caused by the Telnet port in FHEM requiring a password.
If I remove the password from the FHEM Telnet port by deleting the "allowed" Device in FHEM that defines the password for the port, then events are received and there is no crash if I remove the device filter.
Is there a way to add support for password protected Telnet? As far as I understand, it is only necessary to send the password as the first command after opening the Telnet connection.

**Comment by rwrnet** [comment]
The crash you encountered is independent of the password scenario. But when you set a filter, the chance is high it drops all events, triggering the crash. I created a PR.

**Comment by reibuehl** [comment]
Interesting! Thanks for looking into this. If I understand right, even with your change, the password protected access would still not be possible, but the crash should be gone, correct?

**Comment by rwrnet** [comment]
Correct. :)
